# Generated by Django 5.2.7 on 2025-10-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diagnostico.diagnostico')),
            ],
        ),
    ]
