# Generated by Django 5.2.7 on 2025-10-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='estado',
            field=models.CharField(choices=[('NO_ENTREGADO', 'No entregado'), ('ENTREGADO', 'Entregado')], default='NO_ENTREGADO', max_length=20, verbose_name='Estado de entrega'),
        ),
    ]
