# Generated by Django 5.2.7 on 2025-10-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_rol_descripcion_alter_rol_nombre'),
        ('login', '0002_cleanup_duplicate_roles'),
    ]

    operations = [
    ]
