# Generated by Django 5.2.7 on 2025-10-24 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='nombre',
            new_name='cliente',
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo',
            name='problema',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
