# Generated by Django 5.2.7 on 2025-10-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0003_auto_20251024_cleanup_duplicates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={},
        ),
    ]
