# Generated by Django 5.2.7 on 2025-11-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0004_alter_equipo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='cliente',
            field=models.CharField(max_length=100, verbose_name='Nombre del cliente'),
        ),
    ]
