# Generated by Django 5.2.7 on 2025-10-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=100)),
                ('diagnostico', models.TextField()),
                ('solucion', models.TextField()),
                ('tipo_solucion', models.CharField(max_length=100)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='recepcion.equipo')),
            ],
        ),
    ]
