# Generated by Django 5.2.7 on 2025-10-24 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
        ('recepcion', '0002_rename_nombre_equipo_cliente_equipo_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='equipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='recepcion.equipo'),
        ),
    ]
