# Generated by Django 5.2.7 on 2025-10-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0003_estudiante_alter_diagnostico_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='tipo_solucion',
            field=models.CharField(choices=[('correctiva', 'Correctiva'), ('preventiva', 'Preventiva')], max_length=100),
        ),
    ]
