# Generated by Django 5.2.7 on 2025-11-28 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0005_alter_estudiante_nombre_unique'),
        ('recepcion', '0005_alter_equipo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='recepcion.equipo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostico.estudiante')),
            ],
        ),
    ]
